
# This is a basic workflow to help you get started with Actions

name: s3-depl

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'
          cache: 'npm'
          cache-dependency-path: './react/notesmall/package-lock.json'


      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Build React App
        run: |
          
          pwd
          ls
          cd react/notesmall
          npm install
          npm run build
      - name: Deploy app build to S3 bucket
        run: |
          pwd
          pwd
          aws s3 sync ./build/ s3://${{ secrets.AWS_BUCKET_NAME }} --delete
